Update homework.md for 2024
DataTalksClub/machine-learning-zoomcamp pull request #587
Opened 2024-11-01 10:05 UTC by MathmoKiwi

Giving direct link for this week's homework

2024-11-01 15:21 UTC, maxim-eyengue commented on 06-trees/homework.md
You've written `20234`. It would be good correcting the year.

2024-11-02 16:31 UTC, alexkolo requested changes

2024-11-02 16:31 UTC, alexkolo commented on 06-trees/homework.md
> +* For 20234 cohort homework, check [the 2024 cohort folder](../cohorts/2024/06-trees/homework.md)
```suggestion
* For 2024 cohort homework, check [the 2024 cohort folder](../cohorts/2024/06-trees/homework.md)
```

2024-11-03 13:02 UTC, merged

2024-11-03 13:02 UTC, alexeygrigorev commented
Thank you!